### ISSUE TITLE
紙面の図参照番号と図番号がズレている

### ISSUE THREAD

**Issue by muojp** [youten/howto-create-vr-contents#2]
5章以外で図版参照が使われていなかったので終盤に気付いたのですが、ズレていますね。

![inkedfullsizerender_li](https://cloud.githubusercontent.com/assets/766864/24845593/73787cca-1dee-11e7-929e-eed11842b0b9.jpg)

1ファイルに1章から5章までを詰めた結果だと思うました。

**Comment by youten** [comment]
丁寧に写真までありがとうございます、分割して修正しました。
